# LOCAL 3000
GET http://localhost:3000/contacts

###
GET http://localhost:3000/contacts/626a30d54b82aa37ecae1325

###
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Prueba",
    "lastName": "Lopez",
    "email": "denis@gmail.com",
    "favoriteColor": "Black",
    "birthday": "Unknown"
}

###
PUT http://localhost:3000/contacts/627bcc671291ec849bd24088 HTTP/1.1
content-type: application/json

{
    "firstName": "Test",
    "lastName": "Lopez",
    "email": "denis@gmail.com",
    "favoriteColor": "Black",
    "birthday": "Unknown"
}

###
DELETE http://localhost:3000/contacts/627bcc671291ec849bd24088

###

# HEROKU 

GET https://backendcse.herokuapp.com/contacts

###
GET https://backendcse.herokuapp.com/contacts/626a309a4b82aa37ecae1324


###
POST https://backendcse.herokuapp.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Pedro",
    "lastName": "Susano",
    "email": "Pedro@gmail.com",
    "favoriteColor": "Black",
    "birthday": "Unknown"
}
###
PUT https://backendcse.herokuapp.com/contacts/627375b7e0632714fcc99c1f HTTP/1.1
content-type: application/json

{
    "firstName": "Denis",
    "lastName": "Lopez",
    "email": "denis@gmail.com",
    "favoriteColor": "Black",
    "birthday": "Unknown"
}

###
DELETE https://backendcse.herokuapp.com/contacts/627375b7e0632714fcc99c1f

###